(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(aquamacs-additional-fontsets nil t)
 '(aquamacs-customization-version-id 202 t)
 '(aquamacs-tool-bar-user-customization nil t)
 '(auto-revert-interval 10)
 '(auto-save-default t)
 '(auto-save-interval 500)
 '(battery-update-interval 300)
 '(custom-buffer-indent 2)
 '(custom-buffer-sort-alphabetically t)
 '(default-frame-alist (quote ((tool-bar-lines . 0) (vertical-scroll-bars) (fringe) (right-fringe) (left-fringe . 1) (internal-border-width . 0) (cursor-type . box) (menu-bar-lines . 1) (background-color . "#111") (background-mode . dark) (border-color . "#111") (cursor-color . "yellow") (foreground-color . "#ddd") (mouse-color . "sienna1"))))
 '(default-major-mode (quote org-mode))
 '(display-battery-mode t)
 '(display-time-mode t)
 '(eol-mnemonic-mac "(Mac)")
 '(global-auto-revert-mode t)
 '(global-hl-line-mode t)
 '(ido-confirm-unique-completion t)
 '(ido-enable-prefix t)
 '(ido-everywhere t)
 '(ido-use-filename-at-point (quote guess))
 '(iswitchb-mode t)
 '(mail-indentation-spaces 2)
 '(make-backup-files nil)
 '(ns-alternate-modifier (quote meta))
 '(ns-antialias-text nil)
 '(ns-command-modifier (quote super))
 '(ns-tool-bar-display-mode nil t)
 '(ns-tool-bar-size-mode nil t)
 '(nxml-attribute-indent 2)
 '(org-agenda-files (quote ("~/org/pro/mission.org" "~/org/home/home.org")))
 '(org-log-done (quote note))
 '(org-startup-folded (quote content))
 '(perl-continued-brace-offset -2)
 '(perl-continued-statement-offset 2)
 '(perl-indent-level 2)
 '(polling-period 5)
 '(read-buffer-function (quote ido-read-buffer))
 '(safe-local-variable-values (quote ((ruby-indent-level . 2) (byte-compile-warnings not cl-functions) (generated-autoload-file . "cl-loaddefs.el") (require-final-newline))))
 '(server-mode nil)
 '(server-raise-frame nil)
 '(size-indication-mode t)
 '(standard-indent 2)
 '(column-number-mode t)
 '(show-paren-mode t))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:inherit nil :stipple nil :background "#040404" :foreground "#FFFFFF" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight light :height 120 :width condensed :foundry "apple" :family "Monaco"))))
 '(Custom-mode-default ((t (:inherit autoface-default :height 140 :family "DejaVu Sans Mono"))) t)
 '(font-lock-comment-face ((t (:foreground "#9933CC")))))
